"""empty message

Revision ID: 07e88c14c5b5
Revises: 13f59abc09af
Create Date: 2019-08-31 14:26:03.290907

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '07e88c14c5b5'
down_revision = '13f59abc09af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_umi_lcell', table_name='umi')
    op.drop_constraint('umi_lcell_fkey', 'umi', type_='foreignkey')
    op.add_column('umi', sa.Column('center', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True))
    op.add_column('umi', sa.Column('hull', geoalchemy2.types.Geometry(geometry_type='POLYGON'), nullable=True))
    op.add_column('umi', sa.Column('kde_density', geoalchemy2.types.Raster(), nullable=True))
    op.drop_column('umi', 'seg20')
    op.drop_column('umi', 'lcell')

    op.drop_index('ix_linkagecell_dsid', table_name='linkagecell')
    op.drop_table('linkagecell')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('umi', sa.Column('lcell', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('umi', sa.Column('seg20', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('umi_lcell_fkey', 'umi', 'linkagecell', ['lcell'], ['id'], ondelete='CASCADE')
    op.create_index('ix_umi_lcell', 'umi', ['lcell'], unique=False)
    op.drop_column('umi', 'kde_density')
    op.drop_column('umi', 'hull')
    op.drop_column('umi', 'center')
    op.create_table('linkagecell',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dsid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('center', geoalchemy2.types.Geometry(geometry_type='POINT'), autoincrement=False, nullable=True),
    sa.Column('hull', geoalchemy2.types.Geometry(geometry_type='POLYGON'), autoincrement=False, nullable=True),
    sa.Column('kde_density', geoalchemy2.types.Raster(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dsid'], ['dataset.id'], name='linkagecell_dsid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='linkagecell_pkey')
    )
    op.create_index('ix_linkagecell_dsid', 'linkagecell', ['dsid'], unique=False)
    # ### end Alembic commands ###
