"""empty message

Revision ID: 392c367b1fcc
Revises: 4dbe122f627f
Create Date: 2019-09-15 21:56:43.121562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392c367b1fcc'
down_revision = '4dbe122f627f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segment', 'bval')
    op.drop_column('segment', 'gval')
    op.drop_column('segment', 'rval')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segment', sa.Column('rval', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('gval', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('bval', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
