"""empty message

Revision ID: 4f45f4d46c69
Revises: 30599e358883
Create Date: 2019-09-15 20:52:39.929887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f45f4d46c69'
down_revision = '30599e358883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segment', sa.Column('bval', sa.Integer(), nullable=True))
    op.add_column('segment', sa.Column('gval', sa.Integer(), nullable=True))
    op.add_column('segment', sa.Column('rval', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segment', 'rval')
    op.drop_column('segment', 'gval')
    op.drop_column('segment', 'bval')
    # ### end Alembic commands ###
