"""empty message

Revision ID: 674c3f878d96
Revises: 78bf370d7199
Create Date: 2019-09-15 18:51:47.672219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674c3f878d96'
down_revision = '78bf370d7199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('umi', sa.Column('kde_val', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('umi', 'kde_val')
    # ### end Alembic commands ###
