"""empty message

Revision ID: 78bf370d7199
Revises: 07e88c14c5b5
Create Date: 2019-09-08 16:26:14.814871

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '78bf370d7199'
down_revision = '07e88c14c5b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segment', sa.Column('center', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True))
    op.add_column('segment', sa.Column('hull', geoalchemy2.types.Geometry(geometry_type='POLYGON'), nullable=True))
    op.add_column('segment', sa.Column('kde_density', geoalchemy2.types.Raster(), nullable=True))
    op.drop_column('umi', 'center')
    op.drop_column('umi', 'hull')
    op.drop_column('umi', 'kde_density')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('umi', sa.Column('kde_density', geoalchemy2.types.Raster(), autoincrement=False, nullable=True))
    op.add_column('umi', sa.Column('hull', geoalchemy2.types.Geometry(geometry_type='POLYGON'), autoincrement=False, nullable=True))
    op.add_column('umi', sa.Column('center', geoalchemy2.types.Geometry(geometry_type='POINT'), autoincrement=False, nullable=True))
    op.drop_column('segment', 'kde_density')
    op.drop_column('segment', 'hull')
    op.drop_column('segment', 'center')
    # ### end Alembic commands ###
