"""empty message

Revision ID: 870b698311c4
Revises: e712eb3d7778
Create Date: 2019-09-27 15:35:19.630039

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '870b698311c4'
down_revision = 'e712eb3d7778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segment', sa.Column('points12', geoalchemy2.types.Geometry(geometry_type='MULTIPOINT'), nullable=True))
    op.drop_column('segment', 'point12')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segment', sa.Column('point12', geoalchemy2.types.Geometry(geometry_type='MULTIPOINT'), autoincrement=False, nullable=True))
    op.drop_column('segment', 'points12')
    # ### end Alembic commands ###
