"""empty message

Revision ID: 874b620a0c02
Revises: 392c367b1fcc
Create Date: 2019-09-15 21:56:56.169077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874b620a0c02'
down_revision = '392c367b1fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segment', sa.Column('bval', sa.Numeric(), nullable=True))
    op.add_column('segment', sa.Column('gval', sa.Numeric(), nullable=True))
    op.add_column('segment', sa.Column('rval', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segment', 'rval')
    op.drop_column('segment', 'gval')
    op.drop_column('segment', 'bval')
    # ### end Alembic commands ###
