"""empty message

Revision ID: 9c26feb6f829
Revises: 870b698311c4
Create Date: 2019-09-28 14:04:23.171230

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '9c26feb6f829'
down_revision = '870b698311c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segment', sa.Column('points_xym_kde', geoalchemy2.types.Geometry(geometry_type='MULTIPOINTM'), nullable=True))
    op.add_column('segment', sa.Column('points_xym_total_reads', geoalchemy2.types.Geometry(geometry_type='MULTIPOINTM'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segment', 'points_xym_total_reads')
    op.drop_column('segment', 'points_xym_kde')
    # ### end Alembic commands ###
