"""empty message

Revision ID: f27df069f3e0
Revises: be940eea9eb5
Create Date: 2019-08-19 19:20:08.485658

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'f27df069f3e0'
down_revision = 'be940eea9eb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geoedge',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('beacon_id', sa.Integer(), nullable=True),
    sa.Column('n_uei', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['beacon_id'], ['umi.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['umi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geoedge_beacon_id'), 'geoedge', ['beacon_id'], unique=False)
    op.create_index(op.f('ix_geoedge_target_id'), 'geoedge', ['target_id'], unique=False)
    # op.drop_table('spatial_ref_sys')
    op.add_column('umi', sa.Column('xumi_xy', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('umi', 'xumi_xy')
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    op.drop_index(op.f('ix_geoedge_target_id'), table_name='geoedge')
    op.drop_index(op.f('ix_geoedge_beacon_id'), table_name='geoedge')
    op.drop_table('geoedge')
    # ### end Alembic commands ###
